Issue 83
KeiserCorp/Keiser.Metrics.SDK pull request #85
Opened 2021-05-07 22:16 UTC by ish2028

Closes #83

2021-06-10 18:11 UTC, bayssmekanique requested changes
Some slight syntax changes needed for clarity, noted in comments.

- [ ] Move `MetricsSSO` and `MetricsAdmin` into their own files so that their dependencies can be tree shaken from the main build.  I'll make the necessary changes to the build process before merging.
- [ ] I don't like moving all the test to use `MetricsSSO` by default. Please revert all tests and lets figure out a way to perform tests against the API that doesn't require essentially running as `root` for all the tests.  I suspect we'll need to setup some helper functions that can perform specific actions as `MetricsSSO` during the setup, but allow the test to be performed via the core `Metrics` export as much as possible.

2021-06-10 18:11 UTC, bayssmekanique commented on src/session.ts
> +  export async function url (connection: MetricsConnection) {
Where would this be used?

2021-06-10 23:13 UTC, ish2028 commented
> * [ ]  I don't like moving all the test to use `MetricsSSO` by default. Please revert all tests and lets figure out a way to perform tests against the API that doesn't require essentially running as `root` for all the tests.  I suspect we'll need to setup some helper functions that can perform specific actions as `MetricsSSO` during the setup, but allow the test to be performed via the core `Metrics` export as much as possible.

I basically have it they way you explained.  I am using `MetricsSSO`, which extends the core `Metrics`.  My functions in `test/persistent/user.ts` contain the functions that talk with `MetricsSSO` functions and then call a core `Metrics` function to be authenticated.  But just so I am clear you want me to have helper functions that I pass `Metrics`, that will create an instance of `MetricsSSO` without exposing `MetricsSSO` to the test?

2021-06-14 18:49 UTC, bayssmekanique commented
> > * [ ]   I don't like moving all the test to use `MetricsSSO` by default. Please revert all tests and lets figure out a way to perform tests against the API that doesn't require essentially running as `root` for all the tests.  I suspect we'll need to setup some helper functions that can perform specific actions as `MetricsSSO` during the setup, but allow the test to be performed via the core `Metrics` export as much as possible.
> 
> I basically have it they way you explained. I am using `MetricsSSO`, which extends the core `Metrics`. My functions in `test/persistent/user.ts` contain the functions that talk with `MetricsSSO` functions and then call a core `Metrics` function to be authenticated. But just so I am clear you want me to have helper functions that I pass `Metrics`, that will create an instance of `MetricsSSO` without exposing `MetricsSSO` to the test?

Yes, I want a helper function that will spit out an authenticated `Metrics` instance without having to import `MetricsSSO`.

2021-07-09 20:43 UTC, merged